### ISSUE TITLE
yarn start:ios fails

### ISSUE THREAD

**Issue by jaburcodes** [entria/entria-fullstack#51]
```lerna ERR! yarn run ios exited 1 in '@entria/app'
lerna ERR! yarn run ios stdout:
$ react-native run-ios
Found Xcode project ReactNavigationRelay.xcodeproj
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run ios stderr:
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

Command failed: xcrun instruments -s
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH


Error: Command failed: xcrun instruments -s
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:13)
    at Object.runIOS [as func] (/Users/jabur/foton/entria-fullstack/packages/app/node_modules/react-native/local-cli/runIOS/runIOS.js:76:17)
    at Promise.resolve.then (/Users/jabur/foton/entria-fullstack/packages/app/node_modules/react-native/local-cli/cliEntry.js:117:22)

error Command failed with exit code 1.

lerna ERR! yarn run ios exited 1 in '@entria/app'```

**Comment by jaburcodes** [comment]
run:android works properly

**Comment by sibelius** [comment]
Wrong Xcode config in your machine

**Comment by sibelius** [comment]
install command lines tools

check this https://stackoverflow.com/questions/39778607/error-running-react-native-app-from-terminal-ios
